CREATE TABLE Jogadores (
    ID              INT          PRIMARY KEY
                                 NOT NULL,
    Name            VARCHAR (45) NOT NULL,
    Age             INT          NOT NULL,
    Overall         INTENGER     NOT NULL,
    Potential       INTENGER     NOT NULL,
    Preferred_Foot  VARCHAR (10) NOT NULL,
    Weak_Foot       FLOAT        NOT NULL,
    Position        VARCHAR (10) NOT NULL,
    Height          FLOAT        NOT NULL,
    Weight          VARCHAR (10) NOT NULL,
    Finishing       FLOAT        NOT NULL,
    HeadingAccuracy FLOAT        NOT NULL,
    ShortPassing    FLOAT        NOT NULL,
    Volleys         FLOAT        NOT NULL,
    Dribbling       FLOAT        NOT NULL,
    Curve           FLOAT        NOT NULL,
    FKAccuracy      FLOAT        NOT NULL,
    LongPassing     FLOAT        NOT NULL,
    BallControl     FLOAT        NOT NULL,
    Acceleration    FLOAT        NOT NULL,
    SprintSpeed     FLOAT        NOT NULL,
    Agility         FLOAT        NOT NULL,
    Reactions       FLOAT        NOT NULL,
    Balance         FLOAT        NOT NULL,
    ShotPower       FLOAT        NOT NULL,
    Jumping         FLOAT        NOT NULL,
    Stamina         FLOAT        NOT NULL,
    Strength        FLOAT        NOT NULL,
    LongShots       FLOAT        NOT NULL,
    Aggression      FLOAT        NOT NULL,
    Interceptions   FLOAT        NOT NULL,
    Positioning     FLOAT        NOT NULL,
    Vision          FLOAT        NOT NULL,
    Penalties       FLOAT        NOT NULL,
    Composure       FLOAT        NOT NULL,
    Marking         FLOAT        NOT NULL
);
